version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: ims_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ims_user
      POSTGRES_PASSWORD: ims_password
      POSTGRES_DB: ims_db
    ports:
      - "54321:5432"
    volumes:
      - ims_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ims_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ims_redis_data:/data

volumes:
  ims_pg_data:
  ims_redis_data:
